<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE japanesedictionary [

<!ELEMENT japanesedictionary (entry*)>
<!ELEMENT entry (reb*, keb*)>
<!ELEMENT keb (#PCDATA)>
<!ELEMENT reb (#PCDATA)>
<!ELEMENT gloss (#PCDATA)>
<!ATTLIST gloss xml:lang CDATA "eng">
        
]>

<japanesedictionary>
<entry>
<reb>ヽ</reb>
<gloss>repetition mark in katakana</gloss>
</entry>
<entry>
<reb>ヾ</reb>
</entry>
<entry>
<reb>ゝ</reb>
</entry>
<entry>
<reb>ゞ</reb>
</entry>
<entry>
<keb>〃</keb>
<reb>おなじ</reb>
<reb>おなじく</reb>
<gloss>ditto mark</gloss>
</entry>
<entry>
<keb>仝</keb>
<reb>どう</reb>
<gloss>"as above" mark</gloss>
</entry>
<entry>
<keb>々</keb>
<reb>のま</reb>
<reb>ノマ</reb>
</entry>
<entry>
<keb>○</keb>
<keb>〇</keb>
<reb>まる</reb>
<gloss>circle</gloss>
<gloss>"correct"</gloss>
<gloss>"good"</gloss>
<gloss>*</gloss>
<gloss>_</gloss>
<gloss>period</gloss>
<gloss>full stop</gloss>
<gloss>handakuten (diacritic)</gloss>
</entry>
<entry>
<keb>ＡＢＣ順</keb>
<reb>エービーシーじゅん</reb>
<gloss>alphabetical order</gloss>
</entry>
<entry>
<keb>ＣＤプレーヤー</keb>
<keb>ＣＤプレイヤー</keb>
<reb>シーディープレーヤー</reb>
<reb>シーディープレイヤー</reb>
<gloss>CD player</gloss>
</entry>
<entry>
<keb>Ｎ響</keb>
<reb>エヌきょう</reb>
<gloss>NHK Symphony Orchestra</gloss>
</entry>
<entry>
<keb>Ｏバック</keb>
<reb>オーバック</reb>
<gloss>O-back</gloss>
<gloss>skirt with peek-a-boo hole in rump</gloss>
</entry>
<entry>
<keb>Ｔシャツ</keb>
<reb>ティーシャツ</reb>
<gloss>T-shirt</gloss>
<gloss>tee shirt</gloss>
</entry>
<entry>
<keb>Ｔバック</keb>
<reb>ティーバック</reb>
<gloss>T-back</gloss>
<gloss>bikini thong</gloss>
</entry>
<entry>
<keb>あうんの呼吸</keb>
<keb>阿吽の呼吸</keb>
<keb>あ・うんの呼吸</keb>
<reb>あうんのこきゅう</reb>
<gloss>the harmonizing, mentally and physically, of two parties engaged in an activity</gloss>
<gloss>singing from the same hymn-sheet</gloss>
<gloss>dancing to the same beat</gloss>
</entry>
<entry>
<reb>あおば</reb>
<gloss>(former) regular (stops at every station) Tōhoku-line Shinkansen</gloss>
</entry>
<entry>
<keb>明白</keb>
<reb>めいはく</reb>
<gloss>obvious</gloss>
<gloss>clear</gloss>
<gloss>plain</gloss>
<gloss>evident</gloss>
<gloss>apparent</gloss>
<gloss>explicit</gloss>
<gloss>overt</gloss>
</entry>
<entry>
<keb>明白</keb>
<keb>偸閑</keb>
<keb>白地</keb>
<reb>あからさま</reb>
<gloss>plain</gloss>
<gloss>frank</gloss>
<gloss>candid</gloss>
<gloss>open</gloss>
<gloss>direct</gloss>
<gloss>straightforward</gloss>
<gloss>unabashed</gloss>
<gloss>blatant</gloss>
<gloss>flagrant</gloss>
</entry>
<entry>
<keb>明かん</keb>
<reb>あかん</reb>
<reb>アカン</reb>
<gloss>useless</gloss>
<gloss>no good</gloss>
<gloss>hopeless</gloss>
<gloss>cannot</gloss>
<gloss>must not</gloss>
<gloss>not allowed</gloss>
</entry>
<entry>
<keb>悪どい</keb>
<keb>灰汁どい</keb>
<reb>あくどい</reb>
<gloss>gaudy</gloss>
<gloss>showy</gloss>
<gloss>garish</gloss>
<gloss>loud</gloss>
<gloss>crooked</gloss>
<gloss>vicious</gloss>
<gloss>wicked</gloss>
<gloss>nasty</gloss>
<gloss>unscrupulous</gloss>
<gloss>dishonest</gloss>
</entry>
<entry>
<keb>論う</keb>
<reb>あげつらう</reb>
<gloss>to discuss</gloss>
<gloss>to find fault with</gloss>
<gloss>to criticize</gloss>
<gloss>to criticise</gloss>
</entry>
<entry>
<keb>遇う</keb>
<keb>配う</keb>
<reb>あしらう</reb>
<gloss>to treat</gloss>
<gloss>to handle</gloss>
<gloss>to deal with</gloss>
<gloss>to arrange</gloss>
<gloss>to decorate</gloss>
<gloss>to dress</gloss>
<gloss>to garnish</gloss>
</entry>
<entry>
<keb>馬酔木</keb>
<reb>あせび</reb>
<reb>あしび</reb>
<reb>あせぼ</reb>
<reb>あせぶ</reb>
<reb>アセビ</reb>
<gloss>Japanese andromeda (Pieris japonica)</gloss>
<gloss>lily-of-the-valley</gloss>
</entry>
<entry>
<keb>彼処</keb>
<keb>彼所</keb>
<reb>あそこ</reb>
<reb>あすこ</reb>
<reb>かしこ</reb>
<reb>アソコ</reb>
<reb>あしこ</reb>
<reb>あこ</reb>
<gloss>there</gloss>
<gloss>over there</gloss>
<gloss>that place</gloss>
<gloss>yonder</gloss>
<gloss>you-know-where</gloss>
<gloss>genitals</gloss>
<gloss>private parts</gloss>
<gloss>nether regions</gloss>
<gloss>that far</gloss>
<gloss>that much</gloss>
<gloss>that point</gloss>
</entry>
<entry>
<reb>あっさり</reb>
<reb>アッサリ</reb>
<gloss>easily</gloss>
<gloss>readily</gloss>
<gloss>quickly</gloss>
<gloss>flatly (refuse)</gloss>
<gloss>lightly (seasoned food, applied make-up, etc.)</gloss>
<gloss>plainly</gloss>
<gloss>simply</gloss>
</entry>
<entry>
<keb>あっという間に</keb>
<keb>あっと言う間に</keb>
<keb>アッという間に</keb>
<keb>アッと言う間に</keb>
<keb>あっとゆう間に</keb>
<keb>アッとゆう間に</keb>
<reb>あっというまに</reb>
<gloss>in an instant</gloss>
<gloss>in a flash</gloss>
<gloss>in the blink of an eye</gloss>
<gloss>in no time at all</gloss>
<gloss>just like that</gloss>
</entry>
<entry>
<reb>あっぷあっぷ</reb>
<gloss>floundering while nearly drowning</gloss>
<gloss>suffering</gloss>
</entry>
<entry>
<reb>あどけない</reb>
<gloss>innocent</gloss>
<gloss>cherubic</gloss>
<gloss>childlike</gloss>
</entry>
<entry>
<keb>彼の</keb>
<reb>あの</reb>
<reb>あん</reb>
<gloss>that</gloss>
<gloss>those</gloss>
<gloss>the</gloss>
</entry>
<entry>
<reb>あの</reb>
<reb>あのー</reb>
<reb>あのう</reb>
<gloss>say</gloss>
<gloss>well</gloss>
<gloss>um</gloss>
<gloss>er</gloss>
</entry>
<entry>
<keb>あの人</keb>
<keb>彼の人</keb>
<reb>あのひと</reb>
<gloss>he</gloss>
<gloss>she</gloss>
<gloss>that person</gloss>
<gloss>you</gloss>
</entry>
<entry>
<keb>あの方</keb>
<keb>彼の方</keb>
<reb>あのかた</reb>
<gloss>that gentleman</gloss>
<gloss>that lady</gloss>
<gloss>he</gloss>
<gloss>she</gloss>
</entry>
<entry>
<keb>溢れる</keb>
<reb>あぶれる</reb>
<gloss>to fail (in getting a job)</gloss>
<gloss>to miss out (at fishing, hunting, etc.)</gloss>
<gloss>to be left out</gloss>
<gloss>to be crowded out</gloss>
</entry>
<entry>
<reb>あべこべ</reb>
<gloss>contrary</gloss>
<gloss>opposite</gloss>
<gloss>inverse</gloss>
<gloss>reverse</gloss>
<gloss>back-to-front</gloss>
</entry>
<entry>
<keb>阿呆陀羅</keb>
<reb>あほんだら</reb>
<reb>あほだら</reb>
<reb>アホンダラ</reb>
<gloss>fool</gloss>
<gloss>oaf</gloss>
<gloss>airhead</gloss>
</entry>
<entry>
<keb>甘子</keb>
<keb>天魚</keb>
<keb>雨子</keb>
<reb>あまご</reb>
<reb>アマゴ</reb>
<gloss>land-locked variety of red-spotted masu trout (Oncorhynchus masou ishikawae)</gloss>
<gloss>amago</gloss>
</entry>
<entry>
<reb>あやす</reb>
<gloss>to cuddle</gloss>
<gloss>to comfort</gloss>
<gloss>to rock</gloss>
<gloss>to soothe</gloss>
<gloss>to dandle</gloss>
<gloss>to humor</gloss>
<gloss>to humour</gloss>
<gloss>to lull</gloss>
</entry>
<entry>
<reb>あやふや</reb>
<gloss>uncertain</gloss>
<gloss>indefinite</gloss>
<gloss>vague</gloss>
<gloss>ambiguous</gloss>
<gloss>equivocal</gloss>
<gloss>dubious</gloss>
<gloss>doubtful</gloss>
<gloss>non-committal</gloss>
</entry>
<entry>
<reb>あら</reb>
<reb>あらー</reb>
<gloss>oh!</gloss>
<gloss>ah!</gloss>
<gloss>oh no</gloss>
</entry>
<entry>
<keb>𩺊</keb>
<reb>あら</reb>
<reb>アラ</reb>
<gloss>saw-edged perch (Niphon spinosus)</gloss>
</entry>
<entry>
<keb>彼</keb>
<keb>彼れ</keb>
<reb>あれ</reb>
<reb>アレ</reb>
<gloss>that</gloss>
<gloss>that thing</gloss>
<gloss>that person</gloss>
<gloss>then</gloss>
<gloss>that time</gloss>
<gloss>that place (over there)</gloss>
<gloss>down there (i.e. one's genitals)</gloss>
<gloss>period</gloss>
<gloss>menses</gloss>
</entry>
<entry>
<reb>あんな</reb>
<gloss>that sort of</gloss>
<gloss>that kind of</gloss>
<gloss>like that</gloss>
<gloss>such</gloss>
<gloss>so</gloss>
</entry>
<entry>
<keb>いい加減にしなさい</keb>
<reb>いいかげんにしなさい</reb>
<gloss>shape up!</gloss>
<gloss>act properly!</gloss>
</entry>
<entry>
<keb>いい年をして</keb>
<keb>いい歳をして</keb>
<reb>いいとしをして</reb>
<gloss>(in spite of) being old enough to know better</gloss>
</entry>
<entry>
<keb>否々</keb>
<keb>否否</keb>
<reb>いやいや</reb>
<reb>いえいえ</reb>
<gloss>no!</gloss>
<gloss>no no!</gloss>
<gloss>no, not at all</gloss>
</entry>
<entry>
<keb>如何わしい</keb>
<reb>いかがわしい</reb>
<gloss>suspicious</gloss>
<gloss>dubious</gloss>
<gloss>unreliable</gloss>
<gloss>indecent</gloss>
<gloss>unseemly</gloss>
</entry>
<entry>
<reb>いかす</reb>
<reb>イカす</reb>
<gloss>to be smart</gloss>
<gloss>to be cool</gloss>
<gloss>to be sharp</gloss>
<gloss>to be stylish</gloss>
</entry>
<entry>
<keb>いかなる場合でも</keb>
<keb>如何なる場合でも</keb>
<reb>いかなるばあいでも</reb>
<gloss>in any case</gloss>
<gloss>whatever the case may be</gloss>
</entry>
<entry>
<keb>如何にも</keb>
<reb>いかにも</reb>
<gloss>indeed</gloss>
<gloss>really</gloss>
<gloss>truly</gloss>
<gloss>just (like)</gloss>
<gloss>very</gloss>
<gloss>extremely</gloss>
<gloss>totally</gloss>
<gloss>terribly</gloss>
<gloss>absolutely</gloss>
<gloss>certainly</gloss>
<gloss>for sure</gloss>
</entry>
<entry>
<keb>幾つも</keb>
<reb>いくつも</reb>
<gloss>many</gloss>
<gloss>much</gloss>
<gloss>plenty</gloss>
<gloss>hardly</gloss>
</entry>
<entry>
<keb>行けない</keb>
<reb>いけない</reb>
<gloss>bad</gloss>
<gloss>wrong</gloss>
<gloss>naughty</gloss>
<gloss>must not (do, be)</gloss>
<gloss>should not</gloss>
<gloss>ought not to</gloss>
<gloss>useless</gloss>
<gloss>no good</gloss>
<gloss>bad</gloss>
<gloss>hopeless</gloss>
<gloss>beyond hope</gloss>
<gloss>unfortunate</gloss>
<gloss>a shame</gloss>
<gloss>a pity</gloss>
<gloss>unable to drink (alcohol)</gloss>
<gloss>so as not to ...</gloss>
<gloss>so that ... (won't)</gloss>
<gloss>in case ...</gloss>
<gloss>for fear that ...</gloss>
<gloss>lest ...</gloss>
</entry>
<entry>
<reb>いごっそう</reb>
<gloss>stubborn person</gloss>
<gloss>strong-minded person</gloss>
<gloss>obstinate person</gloss>
</entry>
<entry>
<reb>いざ</reb>
<gloss>now</gloss>
<gloss>come (now)</gloss>
<gloss>well</gloss>
</entry>
<entry>
<reb>いざこざ</reb>
<reb>イザコザ</reb>
<gloss>trouble</gloss>
<gloss>quarrel</gloss>
<gloss>difficulties</gloss>
<gloss>complication</gloss>
<gloss>tangle</gloss>
</entry>
<entry>
<reb>イジイジ</reb>
<reb>いじいじ</reb>
<gloss>hesitantly</gloss>
<gloss>timidly</gloss>
<gloss>diffidently</gloss>
</entry>
<entry>
<reb>いじける</reb>
<gloss>to grow timid</gloss>
<gloss>to cower</gloss>
<gloss>to shrink</gloss>
<gloss>to lose one's nerve</gloss>
<gloss>to become perverse</gloss>
<gloss>to become contrary</gloss>
<gloss>to become warped</gloss>
<gloss>to become withdrawn</gloss>
<gloss>to be cramped</gloss>
<gloss>to be constrained</gloss>
</entry>
<entry>
<reb>いじましい</reb>
<reb>いぢましい</reb>
<gloss>stingy</gloss>
<gloss>petty</gloss>
<gloss>pathetic</gloss>
<gloss>lovable</gloss>
<gloss>sweet</gloss>
<gloss>charming</gloss>
<gloss>touching</gloss>
</entry>
<entry>
<reb>いじらしい</reb>
<gloss>lovable</gloss>
<gloss>sweet</gloss>
<gloss>charming</gloss>
<gloss>pitiful</gloss>
<gloss>pathetic</gloss>
<gloss>touching</gloss>
</entry>
<entry>
<keb>いじり回す</keb>
<keb>弄り回す</keb>
<keb>弄りまわす</keb>
<reb>いじりまわす</reb>
<gloss>to tinker with</gloss>
<gloss>to fumble with</gloss>
<gloss>to fiddle with</gloss>
<gloss>to twiddle</gloss>
</entry>
<entry>
<reb>いそいそ</reb>
<reb>イソイソ</reb>
<gloss>cheerfully</gloss>
<gloss>joyously</gloss>
<gloss>joyfully</gloss>
<gloss>happily</gloss>
<gloss>lightheartedly</gloss>
<gloss>excitedly</gloss>
<gloss>eagerly</gloss>
</entry>
<entry>
<reb>イチャイチャ</reb>
<reb>いちゃいちゃ</reb>
<gloss>making out</gloss>
<gloss>necking</gloss>
<gloss>canoodling</gloss>
<gloss>fondling</gloss>
<gloss>flirting</gloss>
</entry>
<entry>
<reb>いちゃつく</reb>
<reb>イチャつく</reb>
<gloss>to make out</gloss>
<gloss>to neck</gloss>
<gloss>to canoodle</gloss>
<gloss>to fondle each other</gloss>
<gloss>to flirt (with)</gloss>
</entry>
<entry>
<keb>何時もより</keb>
<reb>いつもより</reb>
<gloss>more than usual</gloss>
</entry>
<entry>
<keb>いとも簡単に</keb>
<reb>いともかんたんに</reb>
<gloss>very easily</gloss>
</entry>
<entry>
<keb>鯔背</keb>
<reb>いなせ</reb>
<gloss>gallant</gloss>
<gloss>dashing</gloss>
<gloss>smart</gloss>
</entry>
<entry>
<keb>嘶く</keb>
<reb>いななく</reb>
<gloss>to neigh</gloss>
</entry>
<entry>
<keb>嘶き</keb>
<reb>いななき</reb>
<gloss>neigh</gloss>
<gloss>whinny</gloss>
<gloss>bray</gloss>
</entry>
<entry>
<reb>いびる</reb>
<gloss>to pick on</gloss>
<gloss>to tease</gloss>
</entry>
<entry>
<keb>嫌に</keb>
<keb>厭に</keb>
<reb>いやに</reb>
<gloss>awfully</gloss>
<gloss>terribly</gloss>
</entry>
<entry>
<reb>いらっしゃい</reb>
<reb>いらしゃい</reb>
<gloss>come</gloss>
<gloss>go</gloss>
<gloss>stay</gloss>
<gloss>welcome</gloss>
</entry>
<entry>
<reb>いらっしゃいませ</reb>
<reb>いらしゃいませ</reb>
<gloss>welcome</gloss>
</entry>
<entry>
<reb>いらっしゃる</reb>
<gloss>to come</gloss>
<gloss>to go</gloss>
<gloss>to be (somewhere)</gloss>
<gloss>to be (doing)</gloss>
</entry>
<entry>
<reb>うじうじ</reb>
<reb>ウジウジ</reb>
<gloss>indecisively</gloss>
<gloss>hesitantly</gloss>
<gloss>irresolutely</gloss>
<gloss>wishy-washily</gloss>
</entry>
<entry>
<reb>うじゃうじゃ</reb>
<reb>ウジャウジャ</reb>
<gloss>in swarms</gloss>
<gloss>in clusters</gloss>
<gloss>tediously</gloss>
<gloss>slowly</gloss>
</entry>
<entry>
<reb>うずうず</reb>
<reb>ウズウズ</reb>
<gloss>itching to do something</gloss>
<gloss>impatient</gloss>
<gloss>sorely tempted</gloss>
<gloss>eager</gloss>
</entry>
<entry>
<reb>うぞうぞ</reb>
<gloss>irrepressibly aroused (esp. sexually)</gloss>
<gloss>stimulated</gloss>
</entry>
<entry>
<reb>うだうだ</reb>
<reb>ウダウダ</reb>
<gloss>going on and on (about inconsequential things)</gloss>
<gloss>talking nonsense</gloss>
<gloss>idling away the time</gloss>
<gloss>dawdling</gloss>
</entry>
<entry>
<reb>うっかり</reb>
<reb>ウッカリ</reb>
<gloss>carelessly</gloss>
<gloss>thoughtlessly</gloss>
<gloss>inadvertently</gloss>
</entry>
<entry>
<reb>うとうと</reb>
<reb>ウトウト</reb>
<reb>うとっと</reb>
<reb>ウトッと</reb>
<reb>ウトっと</reb>
<gloss>falling into a doze</gloss>
<gloss>dozing off</gloss>
<gloss>nodding off</gloss>
</entry>
<entry>
<reb>うねうね</reb>
<reb>ウネウネ</reb>
<gloss>winding</gloss>
<gloss>meandering</gloss>
<gloss>zigzagging</gloss>
<gloss>zig-zag</gloss>
<gloss>in twists and turns</gloss>
<gloss>sinuously</gloss>
<gloss>tortuously</gloss>
</entry>
<entry>
<keb>畝り</keb>
<reb>うねり</reb>
<gloss>undulation</gloss>
<gloss>winding</gloss>
<gloss>meandering</gloss>
<gloss>swell (of waves)</gloss>
<gloss>ground swell</gloss>
<gloss>surge</gloss>
<gloss>billow</gloss>
<gloss>roller</gloss>
</entry>
<entry>
<reb>うろうろ</reb>
<reb>ウロウロ</reb>
<gloss>restlessly</gloss>
<gloss>aimlessly</gloss>
<gloss>without purpose</gloss>
<gloss>to loiter</gloss>
<gloss>to drift</gloss>
<gloss>to hang about doing nothing</gloss>
<gloss>to wander aimlessly</gloss>
<gloss>to be restless</gloss>
<gloss>to be restless</gloss>
<gloss>to fuss</gloss>
<gloss>to be in a fidget</gloss>
</entry>
<entry>
<keb>狼狽える</keb>
<reb>うろたえる</reb>
<gloss>to be flustered</gloss>
<gloss>to lose one's presence of mind</gloss>
</entry>
<entry>
<reb>うん</reb>
<reb>うむ</reb>
<reb>ううむ</reb>
<gloss>yes</gloss>
<gloss>yeah</gloss>
<gloss>uh huh</gloss>
<gloss>hum</gloss>
<gloss>hmmm</gloss>
<gloss>well</gloss>
<gloss>erm</gloss>
<gloss>huh?</gloss>
<gloss>oof</gloss>
</entry>
<entry>
<reb>うんこ</reb>
<reb>ウンコ</reb>
<gloss>poop</gloss>
<gloss>poo</gloss>
<gloss>faeces</gloss>
<gloss>feces</gloss>
<gloss>crap</gloss>
<gloss>trash</gloss>
<gloss>garbage</gloss>
</entry>
<entry>
<reb>うんざり</reb>
<reb>ウンザリ</reb>
<gloss>tedious</gloss>
<gloss>boring</gloss>
<gloss>being fed up with</gloss>
</entry>
<entry>
<reb>ウンチ</reb>
<reb>うんち</reb>
<gloss>poo</gloss>
<gloss>poop</gloss>
<gloss>doo-doo</gloss>
<gloss>caca</gloss>
<gloss>whoopsie</gloss>
</entry>
<entry>
<keb>鱝</keb>
<keb>鱏</keb>
<keb>海鷂魚</keb>
<reb>えい</reb>
<reb>エイ</reb>
<gloss>ray (any fish of superorder Batoidea)</gloss>
</entry>
<entry>
<reb>ええ</reb>
<reb>えー</reb>
<reb>えーー</reb>
<reb>えーっ</reb>
<gloss>yes</gloss>
<gloss>that is correct</gloss>
<gloss>right</gloss>
<gloss>um</gloss>
<gloss>errr</gloss>
<gloss>well</gloss>
<gloss>huh?</gloss>
<gloss>grrr</gloss>
<gloss>gah</gloss>
<gloss>must I?</gloss>
<gloss>good</gloss>
</entry>
<entry>
<reb>えっと</reb>
<reb>えーと</reb>
<reb>えーっと</reb>
<reb>ええと</reb>
<reb>ええっと</reb>
<reb>えーーっと</reb>
<reb>えーーーっと</reb>
<reb>えーーーーっと</reb>
<gloss>let me see</gloss>
<gloss>well</gloss>
<gloss>errr ...</gloss>
<gloss>uhh ...</gloss>
</entry>
<entry>
<reb>えげつない</reb>
<reb>エゲツない</reb>
<gloss>dirty</gloss>
<gloss>vulgar</gloss>
<gloss>nasty</gloss>
<gloss>offensive</gloss>
<gloss>disgusting</gloss>
</entry>
<entry>
<keb>斉魚</keb>
<reb>えつ</reb>
<reb>エツ</reb>
<gloss>Japanese grenadier anchovy (Coilia nasus)</gloss>
</entry>
<entry>
<keb>お出でになる</keb>
<keb>御出でになる</keb>
<reb>おいでになる</reb>
<gloss>to be</gloss>
<gloss>to come</gloss>
<gloss>to go</gloss>
</entry>
<entry>
<reb>おいでやす</reb>
<gloss>welcome (in shops, etc.)</gloss>
</entry>
<entry>
<reb>おい</reb>
<reb>オイ</reb>
<gloss>hey!</gloss>
<gloss>say!</gloss>
<gloss>I say!</gloss>
<gloss>come on!</gloss>
<gloss>look!</gloss>
<gloss>oi!</gloss>
<gloss>I</gloss>
<gloss>me</gloss>
</entry>
<entry>
<reb>おけさ</reb>
<gloss>style of Japanese folk song associated with Niigata Prefecture</gloss>
</entry>
<entry>
<keb>おけさ節</keb>
<reb>おけさぶし</reb>
<gloss>style of Japanese folk song associated with Niigata Prefecture</gloss>
</entry>
<entry>
<reb>おこしやす</reb>
<gloss>welcome!</gloss>
</entry>
<entry>
<keb>お座なりになる</keb>
<reb>おざなりになる</reb>
<gloss>to not be taken seriously</gloss>
</entry>
<entry>
<reb>おしっこ</reb>
<reb>オシッコ</reb>
<gloss>wee-wee</gloss>
<gloss>pee-pee</gloss>
<gloss>number one</gloss>
</entry>
<entry>
<reb>おしゃぶり</reb>
<gloss>teething ring</gloss>
<gloss>pacifier</gloss>
<gloss>dummy</gloss>
<gloss>blowjob</gloss>
</entry>
<entry>
<keb>悍ましい</keb>
<reb>おぞましい</reb>
<gloss>disgusting</gloss>
<gloss>repulsive</gloss>
</entry>
<entry>
<reb>オタオタ</reb>
<reb>おたおた</reb>
<gloss>flustered</gloss>
<gloss>flurried</gloss>
<gloss>(shocked) speechless</gloss>
</entry>
<entry>
<reb>おちんちん</reb>
<gloss>penis</gloss>
</entry>
<entry>
<reb>おっかない</reb>
<gloss>frightening</gloss>
<gloss>scary</gloss>
<gloss>extreme</gloss>
<gloss>exaggerated</gloss>
<gloss>huge</gloss>
</entry>
<entry>
<keb>落っこちる</keb>
<reb>おっこちる</reb>
<gloss>to fall</gloss>
<gloss>to drop</gloss>
<gloss>to fail (an exam)</gloss>
<gloss>to lose (a contest, election, etc.)</gloss>
<gloss>to be unsuccessful</gloss>
</entry>
<entry>
<reb>おっさん</reb>
<reb>オッサン</reb>
<gloss>middle-aged man</gloss>
<gloss>Buddhist priest</gloss>
</entry>
<entry>
<reb>おっちょこちょい</reb>
<reb>オッチョコチョイ</reb>
<gloss>careless person</gloss>
<gloss>scatterbrain</gloss>
<gloss>birdbrain</gloss>
<gloss>hasty person</gloss>
</entry>
<entry>
<reb>おっぱい</reb>
<reb>オッパイ</reb>
<gloss>boobs</gloss>
<gloss>boobies</gloss>
<gloss>breasts</gloss>
<gloss>tits</gloss>
<gloss>breast milk</gloss>
</entry>
<entry>
<keb>御田</keb>
<keb>お田</keb>
<reb>おでん</reb>
<gloss>oden</gloss>
</entry>
<entry>
<reb>オドオド</reb>
<reb>おどおど</reb>
<gloss>timidly</gloss>
<gloss>nervously</gloss>
<gloss>hesitantly</gloss>
<gloss>trembling (with fear)</gloss>
<gloss>fearfully</gloss>
<gloss>anxiously</gloss>
</entry>
<entry>
<keb>お鍋</keb>
<keb>御鍋</keb>
<reb>おなべ</reb>
<reb>オナベ</reb>
<gloss>pan</gloss>
<gloss>pot</gloss>
<gloss>transgender man (female-to-male)</gloss>
<gloss>butch lesbian</gloss>
<gloss>female transvestite</gloss>
<gloss>maidservant</gloss>
<gloss>housemaid</gloss>
<gloss>night work</gloss>
</entry>
<entry>
<reb>おなら</reb>
<reb>オナラ</reb>
<gloss>wind</gloss>
<gloss>gas</gloss>
<gloss>fart</gloss>
</entry>
<entry>
<reb>おばこ</reb>
<gloss>young girl</gloss>
<gloss>daughter</gloss>
<gloss>unmarried girl</gloss>
</entry>
<entry>
<reb>おべっか</reb>
<gloss>flattery</gloss>
</entry>
<entry>
<reb>おべんちゃら</reb>
<gloss>(excessive) flattery</gloss>
<gloss>smarminess</gloss>
<gloss>fawning</gloss>
</entry>
<entry>
<keb>お負けに</keb>
<keb>御負けに</keb>
<reb>おまけに</reb>
<gloss>to make matters worse</gloss>
<gloss>besides</gloss>
<gloss>what's more</gloss>
<gloss>in addition</gloss>
<gloss>on top of that</gloss>
</entry>
<entry>
<keb>お呪い</keb>
<keb>御呪い</keb>
<keb>お咒い</keb>
<reb>おまじない</reb>
<gloss>good luck charm</gloss>
</entry>
<entry>
<reb>おまんこ</reb>
<reb>オマンコ</reb>
<gloss>pussy</gloss>
<gloss>vulva</gloss>
<gloss>vagina</gloss>
<gloss>sex</gloss>
<gloss>fucking</gloss>
<gloss>screwing</gloss>
</entry>
<entry>
<keb>御襁褓気触れ</keb>
<keb>お襁褓気触れ</keb>
<keb>オムツ気触れ</keb>
<reb>おむつかぶれ</reb>
<reb>オムツかぶれ</reb>
<gloss>diaper rash</gloss>
<gloss>nappy rash</gloss>
</entry>
<entry>
<keb>お粧し</keb>
<keb>御粧し</keb>
<reb>おめかし</reb>
<gloss>dressing up</gloss>
<gloss>putting on makeup</gloss>
<gloss>dolling (oneself) up</gloss>
</entry>
<entry>
<keb>おめでとう御座います</keb>
<keb>御目出度う御座います</keb>
<keb>お目出度うございます</keb>
<reb>おめでとうございます</reb>
<gloss>congratulations</gloss>
</entry>
<entry>
<reb>おや</reb>
<gloss>oh!</gloss>
<gloss>oh?</gloss>
<gloss>my!</gloss>
</entry>
<entry>
<reb>おやおや</reb>
<gloss>my goodness!</gloss>
<gloss>oh my!</gloss>
<gloss>oh dear!</gloss>
</entry>
<entry>
<reb>おろおろ</reb>
<reb>オロオロ</reb>
<gloss>in confusion</gloss>
<gloss>in a fluster</gloss>
<gloss>in bewilderment</gloss>
<gloss>in a dither</gloss>
<gloss>in a panic</gloss>
<gloss>all shook up</gloss>
<gloss>helplessly</gloss>
<gloss>sobbing</gloss>
<gloss>tearfully</gloss>
<gloss>trembling (voice)</gloss>
</entry>
<entry>
<reb>おデブさん</reb>
<reb>おでぶさん</reb>
<gloss>chubby person</gloss>
</entry>
<entry>
<keb>お握り</keb>
<keb>御握り</keb>
<reb>おにぎり</reb>
<gloss>onigiri</gloss>
<gloss>rice ball (often triangular, sometimes with a filling and wrapped in nori)</gloss>
</entry>
<entry>
<keb>お陰</keb>
<keb>お蔭</keb>
<keb>御陰</keb>
<keb>御蔭</keb>
<reb>おかげ</reb>
<gloss>grace (of God)</gloss>
<gloss>benevolence (of Buddha)</gloss>
<gloss>blessing</gloss>
<gloss>assistance</gloss>
<gloss>help</gloss>
<gloss>aid</gloss>
<gloss>effects</gloss>
<gloss>influence</gloss>
</entry>
<entry>
<keb>お陰様</keb>
<keb>お蔭様</keb>
<keb>おかげ様</keb>
<keb>お陰さま</keb>
<keb>御陰様</keb>
<keb>お蔭さま</keb>
<keb>御蔭様</keb>
<reb>おかげさま</reb>
<gloss>(someone's) assistance</gloss>
<gloss>help</gloss>
<gloss>aid</gloss>
<gloss>kindness</gloss>
<gloss>goodwill</gloss>
<gloss>grace (of God)</gloss>
<gloss>benevolence (of Buddha)</gloss>
<gloss>blessing</gloss>
</entry>
<entry>
<keb>お下げ</keb>
<keb>御下げ</keb>
<reb>おさげ</reb>
<gloss>wearing one's hair in braids</gloss>
</entry>
<entry>
<keb>お化け</keb>
<keb>御化け</keb>
<reb>おばけ</reb>
<reb>オバケ</reb>
<gloss>ghost</gloss>
<gloss>apparition</gloss>
<gloss>goblin</gloss>
<gloss>monster</gloss>
<gloss>demon</gloss>
<gloss>something unusually large</gloss>
</entry>
<entry>
<keb>お化け屋敷</keb>
<keb>おばけ屋敷</keb>
<keb>御化け屋敷</keb>
<reb>おばけやしき</reb>
<gloss>haunted house</gloss>
<gloss>spook house</gloss>
<gloss>haunted house (attraction)</gloss>
<gloss>haunted attraction</gloss>
</entry>
<entry>
<keb>お嫁さん</keb>
<reb>およめさん</reb>
<gloss>wife</gloss>
</entry>
<entry>
<keb>お菓子</keb>
<keb>御菓子</keb>
<reb>おかし</reb>
<gloss>confections</gloss>
<gloss>sweets</gloss>
<gloss>candy</gloss>
<gloss>cake</gloss>
</entry>
<entry>
<keb>お願いします</keb>
<keb>御願いします</keb>
<reb>おねがいします</reb>
<gloss>please</gloss>
</entry>
<entry>
<keb>お願いいたします</keb>
<keb>お願い致します</keb>
<keb>御願い致します</keb>
<keb>御願いいたします</keb>
<reb>おねがいいたします</reb>
<gloss>please</gloss>
</entry>
<entry>
<keb>お帰りなさい</keb>
<keb>御帰りなさい</keb>
<reb>おかえりなさい</reb>
<gloss>welcome home</gloss>
</entry>
<entry>
<keb>お気の毒</keb>
<keb>御気の毒</keb>
<keb>お気のどく</keb>
<reb>おきのどく</reb>
<gloss>I am sorry (to hear, to say, etc.)</gloss>
<gloss>a pity</gloss>
</entry>
<entry>
<keb>お客さん</keb>
<keb>御客さん</keb>
<reb>おきゃくさん</reb>
<gloss>guest</gloss>
<gloss>visitor</gloss>
<gloss>customer</gloss>
<gloss>client</gloss>
<gloss>shopper</gloss>
<gloss>spectator</gloss>
<gloss>audience</gloss>
<gloss>tourist</gloss>
<gloss>sightseer</gloss>
<gloss>passenger</gloss>
</entry>
<entry>
<keb>お客様</keb>
<keb>お客さま</keb>
<keb>御客様</keb>
<keb>御客さま</keb>
<reb>おきゃくさま</reb>
<gloss>guest</gloss>
<gloss>visitor</gloss>
<gloss>customer</gloss>
<gloss>client</gloss>
<gloss>shopper</gloss>
<gloss>spectator</gloss>
<gloss>audience</gloss>
<gloss>tourist</gloss>
<gloss>sightseer</gloss>
<gloss>passenger</gloss>
</entry>
<entry>
<keb>お休みなさい</keb>
<keb>御休みなさい</keb>
<reb>おやすみなさい</reb>
<gloss>good night</gloss>
</entry>
<entry>
<keb>お宮</keb>
<reb>おみや</reb>
<gloss>Shinto shrine</gloss>
</entry>
<entry>
<keb>お宮参り</keb>
<keb>御宮参り</keb>
<reb>おみやまいり</reb>
<gloss>miyamairi</gloss>
<gloss>newborn child's first visit to a shrine (within about 30 days of being born)</gloss>
<gloss>visiting a shrine</gloss>
</entry>
<entry>
<keb>お供</keb>
<keb>御供</keb>
<keb>お伴</keb>
<keb>御伴</keb>
<reb>おとも</reb>
<gloss>attendant</gloss>
<gloss>companion</gloss>
</entry>
<entry>
<keb>お金</keb>
<keb>御金</keb>
<reb>おかね</reb>
<gloss>money</gloss>
</entry>
<entry>
<keb>お兄さん</keb>
<keb>御兄さん</keb>
<reb>おにいさん</reb>
<gloss>older brother</gloss>
<gloss>elder brother</gloss>
<gloss>young man</gloss>
<gloss>buddy</gloss>
<gloss>fella</gloss>
<gloss>laddie</gloss>
</entry>
<entry>
<keb>お兄ちゃん</keb>
<keb>御兄ちゃん</keb>
<reb>おにいちゃん</reb>
<gloss>(one's) older brother</gloss>
<gloss>lad</gloss>
<gloss>sonny</gloss>
</entry>
<entry>
<keb>お結び</keb>
<keb>御結び</keb>
<reb>おむすび</reb>
<gloss>onigiri</gloss>
<gloss>rice ball</gloss>
</entry>
<entry>
<keb>お見えになる</keb>
<keb>御見えになる</keb>
<reb>おみえになる</reb>
<gloss>to arrive</gloss>
</entry>
<entry>
<keb>お見舞い</keb>
<keb>お見舞</keb>
<keb>御見舞い</keb>
<keb>御見舞</keb>
<reb>おみまい</reb>
<gloss>calling on someone who is ill</gloss>
<gloss>enquiry</gloss>
<gloss>inquiry</gloss>
</entry>
<entry>
<keb>お古</keb>
<keb>御古</keb>
<reb>おふる</reb>
<gloss>used article (esp. clothes)</gloss>
</entry>
<entry>
<keb>お好み焼き</keb>
<keb>お好み焼</keb>
<keb>御好み焼き</keb>
<keb>御好み焼</keb>
<reb>おこのみやき</reb>
<gloss>okonomiyaki</gloss>
</entry>
<entry>
<keb>お構いなく</keb>
<keb>お構い無く</keb>
<keb>御構い無く</keb>
<keb>御構いなく</keb>
<reb>おかまいなく</reb>
<gloss>please don't fuss over me</gloss>
<gloss>don't go to any trouble</gloss>
<gloss>don't bother</gloss>
</entry>
<entry>
<keb>お絞り</keb>
<keb>御絞り</keb>
<reb>おしぼり</reb>
<gloss>wet towel (supplied at table)</gloss>
<gloss>hot, moistened hand towel</gloss>
</entry>
<entry>
<keb>お札</keb>
<keb>御札</keb>
<reb>おさつ</reb>
<gloss>banknote</gloss>
<gloss>bill</gloss>
<gloss>note</gloss>
</entry>
<entry>
<keb>お雑煮</keb>
<keb>御雑煮</keb>
<reb>おぞうに</reb>
<gloss>soup containing rice cakes and vegetables (New Year's dish)</gloss>
</entry>
<entry>
<keb>お三時</keb>
<keb>御三時</keb>
<reb>おさんじ</reb>
<gloss>afternoon snack (eaten around 3 o'clock)</gloss>
<gloss>afternoon tea</gloss>
</entry>
<entry>
<keb>お参り</keb>
<keb>御参り</keb>
<reb>おまいり</reb>
<gloss>visit (to a shrine, grave, etc.)</gloss>
<gloss>worship</gloss>
</entry>
<entry>
<keb>お産</keb>
<keb>御産</keb>
<reb>おさん</reb>
<gloss>(giving) birth</gloss>
<gloss>childbirth</gloss>
<gloss>delivery</gloss>
</entry>
<entry>
<keb>お仕舞い</keb>
<keb>お終い</keb>
<keb>御仕舞い</keb>
<keb>御終い</keb>
<keb>お仕舞</keb>
<keb>御仕舞</keb>
<reb>おしまい</reb>
<gloss>the end</gloss>
<gloss>closing</gloss>
<gloss>being done for</gloss>
<gloss>that's it</gloss>
<gloss>that's enough</gloss>
<gloss>that's all</gloss>
</entry>
<entry>
<keb>お使い</keb>
<keb>お遣い</keb>
<keb>御使い</keb>
<keb>御遣い</keb>
<keb>お使</keb>
<keb>御使</keb>
<reb>おつかい</reb>
<gloss>errand</gloss>
<gloss>mission</gloss>
<gloss>going on an errand</gloss>
<gloss>messenger</gloss>
<gloss>bearer</gloss>
<gloss>errand boy</gloss>
<gloss>errand girl</gloss>
<gloss>familiar spirit</gloss>
</entry>
<entry>
<keb>お姉さん</keb>
<keb>お姐さん</keb>
<keb>御姉さん</keb>
<keb>御姐さん</keb>
<reb>おねえさん</reb>
<gloss>older sister</gloss>
<gloss>elder sister</gloss>
<gloss>young lady</gloss>
<gloss>miss</gloss>
<gloss>ma'am</gloss>
<gloss>older girl</gloss>
</entry>
<entry>
<keb>お子さん</keb>
<keb>御子さん</keb>
<reb>おこさん</reb>
<gloss>child</gloss>
</entry>
<entry>
<keb>お子様</keb>
<keb>お子さま</keb>
<keb>御子様</keb>
<keb>御子さま</keb>
<reb>おこさま</reb>
<gloss>(another's) child</gloss>
<gloss>child</gloss>
<gloss>kid</gloss>
</entry>
<entry>
<keb>お歯黒</keb>
<keb>鉄漿</keb>
<keb>御歯黒</keb>
<reb>おはぐろ</reb>
<gloss>tooth blackening</gloss>
<gloss>tooth-blackening dye</gloss>
</entry>
<entry>
<keb>お辞儀</keb>
<keb>御辞儀</keb>
<reb>おじぎ</reb>
<gloss>bow</gloss>
<gloss>bowing</gloss>
</entry>
<entry>
<keb>お七夜</keb>
<reb>おしちや</reb>
<gloss>name-giving ceremony</gloss>
</entry>
<entry>
<keb>お邪魔します</keb>
<keb>御邪魔します</keb>
<reb>おじゃまします</reb>
<gloss>please excuse the intrusion</gloss>
<gloss>I'm coming in</gloss>
</entry>
<entry>
<keb>お守り</keb>
<keb>御守り</keb>
<keb>御守</keb>
<keb>お守</keb>
<reb>おまもり</reb>
<gloss>charm</gloss>
<gloss>amulet</gloss>
<gloss>talisman</gloss>
</entry>
<entry>
<keb>お手玉</keb>
<keb>御手玉</keb>
<reb>おてだま</reb>
<gloss>beanbag</gloss>
<gloss>beanbag juggling game</gloss>
<gloss>bobbling the ball</gloss>
</entry>
<entry>
<keb>お手上げ</keb>
<keb>お手あげ</keb>
<keb>御手上げ</keb>
<reb>おてあげ</reb>
<gloss>being done for</gloss>
<gloss>giving up</gloss>
<gloss>being in a hopeless situation</gloss>
<gloss>not knowing what to do</gloss>
<gloss>being brought to one's knees</gloss>
</entry>
<entry>
<keb>お手盛り</keb>
<keb>御手盛り</keb>
<reb>おてもり</reb>
<gloss>making arbitrary decisions which benefit oneself</gloss>
<gloss>self-approved plan</gloss>
</entry>
<entry>
<keb>お手洗い</keb>
<keb>御手洗</keb>
<keb>御手洗い</keb>
<reb>おてあらい</reb>
<gloss>toilet</gloss>
<gloss>restroom</gloss>
<gloss>lavatory</gloss>
<gloss>bathroom</gloss>
</entry>
<entry>
<keb>お手伝いさん</keb>
<keb>御手伝いさん</keb>
<reb>おてつだいさん</reb>
<gloss>maid</gloss>
</entry>
<entry>
<keb>お巡りさん</keb>
<keb>御巡りさん</keb>
<reb>おまわりさん</reb>
<gloss>police officer</gloss>
</entry>
<entry>
<keb>お召し</keb>
<keb>お召</keb>
<keb>御召し</keb>
<keb>御召</keb>
<reb>おめし</reb>
<gloss>summoning</gloss>
<gloss>calling</gloss>
<gloss>riding</gloss>
<gloss>wearing</gloss>
<gloss>dressing</gloss>
<gloss>clothing</gloss>
<gloss>(high-quality) silk crepe (fabric)</gloss>
</entry>
<entry>
<keb>お召し物</keb>
<keb>御召し物</keb>
<reb>おめしもの</reb>
<gloss>clothing</gloss>
</entry>
<entry>
<keb>お勧め</keb>
<keb>お薦め</keb>
<keb>お奨め</keb>
<keb>御勧め</keb>
<keb>御薦め</keb>
<keb>御奨め</keb>
<reb>おすすめ</reb>
<reb>オススメ</reb>
<gloss>recommendation</gloss>
<gloss>advice</gloss>
<gloss>suggestion</gloss>
<gloss>encouragement</gloss>
</entry>
<entry>
<keb>お上りさん</keb>
<reb>おのぼりさん</reb>
<gloss>countryside people (in town)</gloss>
<gloss>visitor from the country</gloss>
<gloss>out-of-towner</gloss>
<gloss>country bumpkin (visiting the big city)</gloss>
<gloss>yokel</gloss>
</entry>
<entry>
<keb>お嬢さん</keb>
<keb>御嬢さん</keb>
<reb>おじょうさん</reb>
<gloss>(another's) daughter</gloss>
<gloss>young lady</gloss>
</entry>
<entry>
<keb>お食い初め</keb>
<keb>御食い初め</keb>
<reb>おくいぞめ</reb>
<gloss>okuizome</gloss>
<gloss>weaning ceremony</gloss>
</entry>
<entry>
<keb>お尻</keb>
<keb>御尻</keb>
<reb>おしり</reb>
<reb>オシリ</reb>
<gloss>bottom</gloss>
<gloss>buttocks</gloss>
<gloss>bidet function (for anal cleansing)</gloss>
</entry>
<entry>
<keb>お寝小</keb>
<keb>御寝小</keb>
<keb>お寝しょ</keb>
<reb>おねしょ</reb>
<reb>オネショ</reb>
<gloss>bed-wetting</gloss>
</entry>
<entry>